---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
spec:
  replicas: "1"
  selector:
    matchLabels:
      app: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      containers:
      - name: cert-manager-controller
        image: quay.io/jetstack/cert-manager-controller:v1.16.2
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
  labels:
    app: cert-manager-webhook
spec:
  replicas: "1"
  selector:
    matchLabels:
      app: cert-manager-webhook
  template:
    metadata:
      labels:
        app: cert-manager-webhook
    spec:
      containers:
      - name: cert-manager-webhook
        image: quay.io/jetstack/cert-manager-webhook:v1.16.2
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
  labels:
    app: cert-manager-webhook
spec:
  type: ClusterIP
  ports:
  - name: https
    port: "443"
    protocol: TCP
    targetPort: "10250"
  selector:
    app: cert-manager-webhook