# This is a template for the secrets needed by Frigate
# In production, use SealedSecrets or External Secrets Operator
apiVersion: v1
kind: Secret
metadata:
  name: ${app.name}-secrets
  namespace: ${app.namespace}
  labels:
    app.kubernetes.io/name: ${app.name}
    app.kubernetes.io/instance: ${app.name}
    app.kubernetes.io/managed-by: kurel
type: Opaque
stringData:
  plus-api-key: "CHANGE_ME"  # Replace with actual Frigate Plus API key
---
apiVersion: v1
kind: Secret
metadata:
  name: ${app.name}-camera-secrets
  namespace: ${app.namespace}
  labels:
    app.kubernetes.io/name: ${app.name}
    app.kubernetes.io/instance: ${app.name}
    app.kubernetes.io/managed-by: kurel
type: Opaque
stringData:
  cam0-password: "CHANGE_ME"
  cam1-password: "CHANGE_ME"
  cam2-password: "CHANGE_ME"
  cam3-password: "CHANGE_ME"
  cam360-password: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: mqttuser
  namespace: ${app.namespace}
  labels:
    app.kubernetes.io/name: ${app.name}
    app.kubernetes.io/instance: ${app.name}
    app.kubernetes.io/managed-by: kurel
type: Opaque
stringData:
  FRIGATE_MQTT_PASSWORD: "CHANGE_ME"