# golangci-lint configuration for Kure
# Aligned with Wharf standard (meta/standards/golangci-lint.md)

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters (always enabled)
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - gofmt
    - goimports
    - misspell
    - nilerr
    - unconvert
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  exhaustive:
    default-signifies-exhaustive: true

  goimports:
    local-prefixes: github.com/go-kure/kure

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Test files have relaxed rules
    - path: _test\.go
      linters:
        - errcheck
