version: 2
project_name: kure

before:
  hooks:
    - go mod tidy

builds:
  - id: kure
    main: ./cmd/kure
    binary: kure
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/go-kure/kure/pkg/cmd/shared.Version={{.Version}}
      - -X github.com/go-kure/kure/pkg/cmd/shared.GitCommit={{.ShortCommit}}
      - -X github.com/go-kure/kure/pkg/cmd/shared.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

  - id: kurel
    main: ./cmd/kurel
    binary: kurel
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/go-kure/kure/pkg/cmd/shared.Version={{.Version}}
      - -X github.com/go-kure/kure/pkg/cmd/shared.GitCommit={{.ShortCommit}}
      - -X github.com/go-kure/kure/pkg/cmd/shared.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - id: kure-archive
    ids: [kure]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "kure_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: kurel-archive
    ids: [kurel]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "kurel_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

# Generate Software Bill of Materials for supply chain security
sboms:
  - artifacts: archive
    documents:
      - "${artifact}.sbom.json"

# Sign checksums with cosign for artifact verification
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

release:
  github:
    owner: go-kure
    name: kure
  draft: false
  prerelease: auto

# Disable built-in changelog - we use git-cliff for CHANGELOG.md
changelog:
  disable: true
