version: 2
project_name: kure

before:
  hooks:
    - go mod tidy

builds:
  - id: kure
    main: ./cmd/kure
    binary: kure
    ldflags:
      - -s -w
      - -X github.com/go-kure/kure/pkg/cmd/shared.Version={{.Version}}
      - -X github.com/go-kure/kure/pkg/cmd/shared.GitCommit={{.ShortCommit}}
      - -X github.com/go-kure/kure/pkg/cmd/shared.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

  - id: kurel
    main: ./cmd/kurel
    binary: kurel
    ldflags:
      - -s -w
      - -X github.com/go-kure/kure/pkg/cmd/shared.Version={{.Version}}
      - -X github.com/go-kure/kure/pkg/cmd/shared.GitCommit={{.ShortCommit}}
      - -X github.com/go-kure/kure/pkg/cmd/shared.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - id: kure-archive
    ids: [kure]
    formats: [tar.gz]
    name_template: "kure_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: kurel-archive
    ids: [kurel]
    formats: [tar.gz]
    name_template: "kurel_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: go-kure
    name: kure
  draft: false
  prerelease: auto

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
