// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package cnpg

import (
	"testing"

	"sigs.k8s.io/controller-runtime/pkg/client"
)

func TestGeneratedConstructors(t *testing.T) {
	cases := []struct {
		kind       string
		namespaced bool
		obj        client.Object
	}{
		{"Backup", true, CreateBackup("name", "ns")},
		{"Cluster", true, CreateCluster("name", "ns")},
		{"ClusterImageCatalog", false, CreateClusterImageCatalog("name")},
		{"Database", true, CreateDatabase("name", "ns")},
		{"DatabaseRole", true, CreateDatabaseRole("name", "ns")},
		{"FailoverQuorum", true, CreateFailoverQuorum("name", "ns")},
		{"ImageCatalog", true, CreateImageCatalog("name", "ns")},
		{"ObjectStore", true, CreateObjectStore("name", "ns")},
		{"Pooler", true, CreatePooler("name", "ns")},
		{"Publication", true, CreatePublication("name", "ns")},
		{"ScheduledBackup", true, CreateScheduledBackup("name", "ns")},
		{"Subscription", true, CreateSubscription("name", "ns")},
	}
	for _, c := range cases {
		t.Run(c.kind, func(t *testing.T) {
			if got := c.obj.GetObjectKind().GroupVersionKind().Kind; got != c.kind {
				t.Errorf("kind = %q, want %q", got, c.kind)
			}
			wantNS := ""
			if c.namespaced {
				wantNS = "ns"
			}
			if c.obj.GetName() != "name" || c.obj.GetNamespace() != wantNS {
				t.Errorf("identity = %s/%s, want %s/name", c.obj.GetNamespace(), c.obj.GetName(), wantNS)
			}
		})
	}
}
