// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package cnpg

import (
	cloudnativepgv1 "github.com/cloudnative-pg/cloudnative-pg/api/v1"
	pluginbarmancloudv1 "github.com/cloudnative-pg/plugin-barman-cloud/api/v1"

	"github.com/go-kure/kure/pkg/kubernetes"
)

// CreateBackup returns a postgresql.cnpg.io/v1 Backup carrying TypeMeta and identity only.
func CreateBackup(name, namespace string) *cloudnativepgv1.Backup {
	return kubernetes.Create[cloudnativepgv1.Backup](name, namespace)
}

// CreateCluster returns a postgresql.cnpg.io/v1 Cluster carrying TypeMeta and identity only.
func CreateCluster(name, namespace string) *cloudnativepgv1.Cluster {
	return kubernetes.Create[cloudnativepgv1.Cluster](name, namespace)
}

// CreateClusterImageCatalog returns a cluster-scoped postgresql.cnpg.io/v1 ClusterImageCatalog carrying TypeMeta and identity only.
func CreateClusterImageCatalog(name string) *cloudnativepgv1.ClusterImageCatalog {
	return kubernetes.Create[cloudnativepgv1.ClusterImageCatalog](name, "")
}

// CreateDatabase returns a postgresql.cnpg.io/v1 Database carrying TypeMeta and identity only.
func CreateDatabase(name, namespace string) *cloudnativepgv1.Database {
	return kubernetes.Create[cloudnativepgv1.Database](name, namespace)
}

// CreateDatabaseRole returns a postgresql.cnpg.io/v1 DatabaseRole carrying TypeMeta and identity only.
func CreateDatabaseRole(name, namespace string) *cloudnativepgv1.DatabaseRole {
	return kubernetes.Create[cloudnativepgv1.DatabaseRole](name, namespace)
}

// CreateFailoverQuorum returns a postgresql.cnpg.io/v1 FailoverQuorum carrying TypeMeta and identity only.
func CreateFailoverQuorum(name, namespace string) *cloudnativepgv1.FailoverQuorum {
	return kubernetes.Create[cloudnativepgv1.FailoverQuorum](name, namespace)
}

// CreateImageCatalog returns a postgresql.cnpg.io/v1 ImageCatalog carrying TypeMeta and identity only.
func CreateImageCatalog(name, namespace string) *cloudnativepgv1.ImageCatalog {
	return kubernetes.Create[cloudnativepgv1.ImageCatalog](name, namespace)
}

// CreateObjectStore returns a barmancloud.cnpg.io/v1 ObjectStore carrying TypeMeta and identity only.
func CreateObjectStore(name, namespace string) *pluginbarmancloudv1.ObjectStore {
	return kubernetes.Create[pluginbarmancloudv1.ObjectStore](name, namespace)
}

// CreatePooler returns a postgresql.cnpg.io/v1 Pooler carrying TypeMeta and identity only.
func CreatePooler(name, namespace string) *cloudnativepgv1.Pooler {
	return kubernetes.Create[cloudnativepgv1.Pooler](name, namespace)
}

// CreatePublication returns a postgresql.cnpg.io/v1 Publication carrying TypeMeta and identity only.
func CreatePublication(name, namespace string) *cloudnativepgv1.Publication {
	return kubernetes.Create[cloudnativepgv1.Publication](name, namespace)
}

// CreateScheduledBackup returns a postgresql.cnpg.io/v1 ScheduledBackup carrying TypeMeta and identity only.
func CreateScheduledBackup(name, namespace string) *cloudnativepgv1.ScheduledBackup {
	return kubernetes.Create[cloudnativepgv1.ScheduledBackup](name, namespace)
}

// CreateSubscription returns a postgresql.cnpg.io/v1 Subscription carrying TypeMeta and identity only.
func CreateSubscription(name, namespace string) *cloudnativepgv1.Subscription {
	return kubernetes.Create[cloudnativepgv1.Subscription](name, namespace)
}
