// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package kubernetes_test

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/go-kure/kure/pkg/kubernetes"
	"github.com/go-kure/kure/pkg/kubernetes/certmanager"
	"github.com/go-kure/kure/pkg/kubernetes/cilium"
	"github.com/go-kure/kure/pkg/kubernetes/cnpg"
	"github.com/go-kure/kure/pkg/kubernetes/externalsecrets"
	"github.com/go-kure/kure/pkg/kubernetes/fluxcd"
	"github.com/go-kure/kure/pkg/kubernetes/metallb"
	"github.com/go-kure/kure/pkg/kubernetes/prometheus"
	"github.com/go-kure/kure/pkg/kubernetes/volsync"
)

// generatedKind pairs a registered GVK with its generated constructor wrapper.
type generatedKind struct {
	GVK        schema.GroupVersionKind
	Namespaced bool
	Create     func(name, namespace string) client.Object
}

// generatedKinds lists every generated wrapper; the identity test walks the
// scheme and fails on any registered kind missing here.
var generatedKinds = []generatedKind{
	{GVK: schema.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "BackendTLSPolicy"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateBackendTLSPolicy(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "Binding"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateBinding(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "storage.k8s.io", Version: "v1", Kind: "CSIDriver"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateCSIDriver(name) }},
	{GVK: schema.GroupVersionKind{Group: "storage.k8s.io", Version: "v1", Kind: "CSINode"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateCSINode(name) }},
	{GVK: schema.GroupVersionKind{Group: "storage.k8s.io", Version: "v1", Kind: "CSIStorageCapacity"}, Namespaced: true, Create: func(name, namespace string) client.Object {
		return kubernetes.CreateCSIStorageCapacity(name, namespace)
	}},
	{GVK: schema.GroupVersionKind{Group: "rbac.authorization.k8s.io", Version: "v1", Kind: "ClusterRole"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateClusterRole(name) }},
	{GVK: schema.GroupVersionKind{Group: "rbac.authorization.k8s.io", Version: "v1", Kind: "ClusterRoleBinding"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateClusterRoleBinding(name) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "ComponentStatus"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateComponentStatus(name) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "ConfigMap"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateConfigMap(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "apps", Version: "v1", Kind: "ControllerRevision"}, Namespaced: true, Create: func(name, namespace string) client.Object {
		return kubernetes.CreateControllerRevision(name, namespace)
	}},
	{GVK: schema.GroupVersionKind{Group: "batch", Version: "v1", Kind: "CronJob"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateCronJob(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "apiextensions.k8s.io", Version: "v1", Kind: "CustomResourceDefinition"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateCustomResourceDefinition(name) }},
	{GVK: schema.GroupVersionKind{Group: "apps", Version: "v1", Kind: "DaemonSet"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateDaemonSet(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "apps", Version: "v1", Kind: "Deployment"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateDeployment(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "Endpoints"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateEndpoints(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "Event"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateEvent(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "policy", Version: "v1", Kind: "Eviction"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateEviction(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "GRPCRoute"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateGRPCRoute(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "Gateway"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateGateway(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "GatewayClass"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateGatewayClass(name) }},
	{GVK: schema.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "HTTPRoute"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateHTTPRoute(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "autoscaling", Version: "v2", Kind: "HorizontalPodAutoscaler"}, Namespaced: true, Create: func(name, namespace string) client.Object {
		return kubernetes.CreateHorizontalPodAutoscaler(name, namespace)
	}},
	{GVK: schema.GroupVersionKind{Group: "networking.k8s.io", Version: "v1", Kind: "IPAddress"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateIPAddress(name) }},
	{GVK: schema.GroupVersionKind{Group: "networking.k8s.io", Version: "v1", Kind: "Ingress"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateIngress(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "networking.k8s.io", Version: "v1", Kind: "IngressClass"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateIngressClass(name) }},
	{GVK: schema.GroupVersionKind{Group: "batch", Version: "v1", Kind: "Job"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateJob(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "LimitRange"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateLimitRange(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "ListenerSet"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateListenerSet(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "Namespace"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateNamespace(name) }},
	{GVK: schema.GroupVersionKind{Group: "networking.k8s.io", Version: "v1", Kind: "NetworkPolicy"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateNetworkPolicy(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "Node"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateNode(name) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "PersistentVolume"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreatePersistentVolume(name) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "PersistentVolumeClaim"}, Namespaced: true, Create: func(name, namespace string) client.Object {
		return kubernetes.CreatePersistentVolumeClaim(name, namespace)
	}},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "Pod"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreatePod(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "policy", Version: "v1", Kind: "PodDisruptionBudget"}, Namespaced: true, Create: func(name, namespace string) client.Object {
		return kubernetes.CreatePodDisruptionBudget(name, namespace)
	}},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "PodTemplate"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreatePodTemplate(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "RangeAllocation"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateRangeAllocation(name) }},
	{GVK: schema.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "ReferenceGrant"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateReferenceGrant(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "apps", Version: "v1", Kind: "ReplicaSet"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateReplicaSet(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "ReplicationController"}, Namespaced: true, Create: func(name, namespace string) client.Object {
		return kubernetes.CreateReplicationController(name, namespace)
	}},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "ResourceQuota"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateResourceQuota(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "rbac.authorization.k8s.io", Version: "v1", Kind: "Role"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateRole(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "rbac.authorization.k8s.io", Version: "v1", Kind: "RoleBinding"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateRoleBinding(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "Secret"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateSecret(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "Service"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateService(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "", Version: "v1", Kind: "ServiceAccount"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateServiceAccount(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "networking.k8s.io", Version: "v1", Kind: "ServiceCIDR"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateServiceCIDR(name) }},
	{GVK: schema.GroupVersionKind{Group: "apps", Version: "v1", Kind: "StatefulSet"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateStatefulSet(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "storage.k8s.io", Version: "v1", Kind: "StorageClass"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateStorageClass(name) }},
	{GVK: schema.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "TCPRoute"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateTCPRoute(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "TLSRoute"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateTLSRoute(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "UDPRoute"}, Namespaced: true, Create: func(name, namespace string) client.Object { return kubernetes.CreateUDPRoute(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "storage.k8s.io", Version: "v1", Kind: "VolumeAttachment"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateVolumeAttachment(name) }},
	{GVK: schema.GroupVersionKind{Group: "storage.k8s.io", Version: "v1", Kind: "VolumeAttributesClass"}, Namespaced: false, Create: func(name, _ string) client.Object { return kubernetes.CreateVolumeAttributesClass(name) }},
	{GVK: schema.GroupVersionKind{Group: "cert-manager.io", Version: "v1", Kind: "Certificate"}, Namespaced: true, Create: func(name, namespace string) client.Object { return certmanager.CreateCertificate(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "cert-manager.io", Version: "v1", Kind: "CertificateRequest"}, Namespaced: true, Create: func(name, namespace string) client.Object {
		return certmanager.CreateCertificateRequest(name, namespace)
	}},
	{GVK: schema.GroupVersionKind{Group: "acme.cert-manager.io", Version: "v1", Kind: "Challenge"}, Namespaced: true, Create: func(name, namespace string) client.Object { return certmanager.CreateChallenge(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "cert-manager.io", Version: "v1", Kind: "ClusterIssuer"}, Namespaced: false, Create: func(name, _ string) client.Object { return certmanager.CreateClusterIssuer(name) }},
	{GVK: schema.GroupVersionKind{Group: "cert-manager.io", Version: "v1", Kind: "Issuer"}, Namespaced: true, Create: func(name, namespace string) client.Object { return certmanager.CreateIssuer(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "acme.cert-manager.io", Version: "v1", Kind: "Order"}, Namespaced: true, Create: func(name, namespace string) client.Object { return certmanager.CreateOrder(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumBGPAdvertisement"}, Namespaced: false, Create: func(name, _ string) client.Object { return cilium.CreateCiliumBGPAdvertisement(name) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumBGPClusterConfig"}, Namespaced: false, Create: func(name, _ string) client.Object { return cilium.CreateCiliumBGPClusterConfig(name) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumBGPNodeConfig"}, Namespaced: false, Create: func(name, _ string) client.Object { return cilium.CreateCiliumBGPNodeConfig(name) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumBGPNodeConfigOverride"}, Namespaced: false, Create: func(name, _ string) client.Object { return cilium.CreateCiliumBGPNodeConfigOverride(name) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumBGPPeerConfig"}, Namespaced: false, Create: func(name, _ string) client.Object { return cilium.CreateCiliumBGPPeerConfig(name) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumCIDRGroup"}, Namespaced: false, Create: func(name, _ string) client.Object { return cilium.CreateCiliumCIDRGroup(name) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumClusterwideEnvoyConfig"}, Namespaced: false, Create: func(name, _ string) client.Object { return cilium.CreateCiliumClusterwideEnvoyConfig(name) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumClusterwideNetworkPolicy"}, Namespaced: false, Create: func(name, _ string) client.Object { return cilium.CreateCiliumClusterwideNetworkPolicy(name) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumEgressGatewayPolicy"}, Namespaced: false, Create: func(name, _ string) client.Object { return cilium.CreateCiliumEgressGatewayPolicy(name) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumEndpoint"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cilium.CreateCiliumEndpoint(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumEnvoyConfig"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cilium.CreateCiliumEnvoyConfig(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumIdentity"}, Namespaced: false, Create: func(name, _ string) client.Object { return cilium.CreateCiliumIdentity(name) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumLoadBalancerIPPool"}, Namespaced: false, Create: func(name, _ string) client.Object { return cilium.CreateCiliumLoadBalancerIPPool(name) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumLocalRedirectPolicy"}, Namespaced: true, Create: func(name, namespace string) client.Object {
		return cilium.CreateCiliumLocalRedirectPolicy(name, namespace)
	}},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumNetworkPolicy"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cilium.CreateCiliumNetworkPolicy(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumNode"}, Namespaced: false, Create: func(name, _ string) client.Object { return cilium.CreateCiliumNode(name) }},
	{GVK: schema.GroupVersionKind{Group: "cilium.io", Version: "v2", Kind: "CiliumNodeConfig"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cilium.CreateCiliumNodeConfig(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "postgresql.cnpg.io", Version: "v1", Kind: "Backup"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cnpg.CreateBackup(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "postgresql.cnpg.io", Version: "v1", Kind: "Cluster"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cnpg.CreateCluster(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "postgresql.cnpg.io", Version: "v1", Kind: "ClusterImageCatalog"}, Namespaced: false, Create: func(name, _ string) client.Object { return cnpg.CreateClusterImageCatalog(name) }},
	{GVK: schema.GroupVersionKind{Group: "postgresql.cnpg.io", Version: "v1", Kind: "Database"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cnpg.CreateDatabase(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "postgresql.cnpg.io", Version: "v1", Kind: "DatabaseRole"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cnpg.CreateDatabaseRole(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "postgresql.cnpg.io", Version: "v1", Kind: "FailoverQuorum"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cnpg.CreateFailoverQuorum(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "postgresql.cnpg.io", Version: "v1", Kind: "ImageCatalog"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cnpg.CreateImageCatalog(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "barmancloud.cnpg.io", Version: "v1", Kind: "ObjectStore"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cnpg.CreateObjectStore(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "postgresql.cnpg.io", Version: "v1", Kind: "Pooler"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cnpg.CreatePooler(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "postgresql.cnpg.io", Version: "v1", Kind: "Publication"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cnpg.CreatePublication(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "postgresql.cnpg.io", Version: "v1", Kind: "ScheduledBackup"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cnpg.CreateScheduledBackup(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "postgresql.cnpg.io", Version: "v1", Kind: "Subscription"}, Namespaced: true, Create: func(name, namespace string) client.Object { return cnpg.CreateSubscription(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "external-secrets.io", Version: "v1", Kind: "ClusterExternalSecret"}, Namespaced: false, Create: func(name, _ string) client.Object { return externalsecrets.CreateClusterExternalSecret(name) }},
	{GVK: schema.GroupVersionKind{Group: "external-secrets.io", Version: "v1", Kind: "ClusterSecretStore"}, Namespaced: false, Create: func(name, _ string) client.Object { return externalsecrets.CreateClusterSecretStore(name) }},
	{GVK: schema.GroupVersionKind{Group: "external-secrets.io", Version: "v1", Kind: "ExternalSecret"}, Namespaced: true, Create: func(name, namespace string) client.Object {
		return externalsecrets.CreateExternalSecret(name, namespace)
	}},
	{GVK: schema.GroupVersionKind{Group: "external-secrets.io", Version: "v1", Kind: "SecretStore"}, Namespaced: true, Create: func(name, namespace string) client.Object { return externalsecrets.CreateSecretStore(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "notification.toolkit.fluxcd.io", Version: "v1beta3", Kind: "Alert"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateAlert(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "source.extensions.fluxcd.io", Version: "v1beta1", Kind: "ArtifactGenerator"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateArtifactGenerator(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "source.toolkit.fluxcd.io", Version: "v1", Kind: "Bucket"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateBucket(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "source.toolkit.fluxcd.io", Version: "v1", Kind: "ExternalArtifact"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateExternalArtifact(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "fluxcd.controlplane.io", Version: "v1", Kind: "FluxInstance"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateFluxInstance(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "fluxcd.controlplane.io", Version: "v1", Kind: "FluxReport"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateFluxReport(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "source.toolkit.fluxcd.io", Version: "v1", Kind: "GitRepository"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateGitRepository(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "source.toolkit.fluxcd.io", Version: "v1", Kind: "HelmChart"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateHelmChart(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "helm.toolkit.fluxcd.io", Version: "v2", Kind: "HelmRelease"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateHelmRelease(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "source.toolkit.fluxcd.io", Version: "v1", Kind: "HelmRepository"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateHelmRepository(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "image.toolkit.fluxcd.io", Version: "v1", Kind: "ImageUpdateAutomation"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateImageUpdateAutomation(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "kustomize.toolkit.fluxcd.io", Version: "v1", Kind: "Kustomization"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateKustomization(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "source.toolkit.fluxcd.io", Version: "v1", Kind: "OCIRepository"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateOCIRepository(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "notification.toolkit.fluxcd.io", Version: "v1beta3", Kind: "Provider"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateProvider(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "notification.toolkit.fluxcd.io", Version: "v1", Kind: "Receiver"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateReceiver(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "fluxcd.controlplane.io", Version: "v1", Kind: "ResourceSet"}, Namespaced: true, Create: func(name, namespace string) client.Object { return fluxcd.CreateResourceSet(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "fluxcd.controlplane.io", Version: "v1", Kind: "ResourceSetInputProvider"}, Namespaced: true, Create: func(name, namespace string) client.Object {
		return fluxcd.CreateResourceSetInputProvider(name, namespace)
	}},
	{GVK: schema.GroupVersionKind{Group: "metallb.io", Version: "v1beta1", Kind: "BFDProfile"}, Namespaced: true, Create: func(name, namespace string) client.Object { return metallb.CreateBFDProfile(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "metallb.io", Version: "v1beta1", Kind: "BGPAdvertisement"}, Namespaced: true, Create: func(name, namespace string) client.Object { return metallb.CreateBGPAdvertisement(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "metallb.io", Version: "v1beta1", Kind: "BGPPeer"}, Namespaced: true, Create: func(name, namespace string) client.Object { return metallb.CreateBGPPeer(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "metallb.io", Version: "v1beta1", Kind: "Community"}, Namespaced: true, Create: func(name, namespace string) client.Object { return metallb.CreateCommunity(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "metallb.io", Version: "v1beta1", Kind: "ConfigurationState"}, Namespaced: true, Create: func(name, namespace string) client.Object { return metallb.CreateConfigurationState(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "metallb.io", Version: "v1beta1", Kind: "IPAddressPool"}, Namespaced: true, Create: func(name, namespace string) client.Object { return metallb.CreateIPAddressPool(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "metallb.io", Version: "v1beta1", Kind: "L2Advertisement"}, Namespaced: true, Create: func(name, namespace string) client.Object { return metallb.CreateL2Advertisement(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "metallb.io", Version: "v1beta1", Kind: "ServiceBGPStatus"}, Namespaced: true, Create: func(name, namespace string) client.Object { return metallb.CreateServiceBGPStatus(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "metallb.io", Version: "v1beta1", Kind: "ServiceL2Status"}, Namespaced: true, Create: func(name, namespace string) client.Object { return metallb.CreateServiceL2Status(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "monitoring.coreos.com", Version: "v1", Kind: "Alertmanager"}, Namespaced: true, Create: func(name, namespace string) client.Object { return prometheus.CreateAlertmanager(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "monitoring.coreos.com", Version: "v1", Kind: "PodMonitor"}, Namespaced: true, Create: func(name, namespace string) client.Object { return prometheus.CreatePodMonitor(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "monitoring.coreos.com", Version: "v1", Kind: "Probe"}, Namespaced: true, Create: func(name, namespace string) client.Object { return prometheus.CreateProbe(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "monitoring.coreos.com", Version: "v1", Kind: "Prometheus"}, Namespaced: true, Create: func(name, namespace string) client.Object { return prometheus.CreatePrometheus(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "monitoring.coreos.com", Version: "v1", Kind: "PrometheusRule"}, Namespaced: true, Create: func(name, namespace string) client.Object { return prometheus.CreatePrometheusRule(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "monitoring.coreos.com", Version: "v1", Kind: "ServiceMonitor"}, Namespaced: true, Create: func(name, namespace string) client.Object { return prometheus.CreateServiceMonitor(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "monitoring.coreos.com", Version: "v1", Kind: "ThanosRuler"}, Namespaced: true, Create: func(name, namespace string) client.Object { return prometheus.CreateThanosRuler(name, namespace) }},
	{GVK: schema.GroupVersionKind{Group: "volsync.backube", Version: "v1alpha1", Kind: "ReplicationDestination"}, Namespaced: true, Create: func(name, namespace string) client.Object {
		return volsync.CreateReplicationDestination(name, namespace)
	}},
	{GVK: schema.GroupVersionKind{Group: "volsync.backube", Version: "v1alpha1", Kind: "ReplicationSource"}, Namespaced: true, Create: func(name, namespace string) client.Object { return volsync.CreateReplicationSource(name, namespace) }},
}
