// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package kubernetes

import (
	appsv1 "k8s.io/api/apps/v1"
	autoscalingv2 "k8s.io/api/autoscaling/v2"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	policyv1 "k8s.io/api/policy/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	storagev1 "k8s.io/api/storage/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	gatewayapiv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// CreateBackendTLSPolicy returns a gateway.networking.k8s.io/v1 BackendTLSPolicy carrying TypeMeta and identity only.
func CreateBackendTLSPolicy(name, namespace string) *gatewayapiv1.BackendTLSPolicy {
	return Create[gatewayapiv1.BackendTLSPolicy](name, namespace)
}

// CreateBinding returns a v1 Binding carrying TypeMeta and identity only.
func CreateBinding(name, namespace string) *corev1.Binding {
	return Create[corev1.Binding](name, namespace)
}

// CreateCSIDriver returns a cluster-scoped storage.k8s.io/v1 CSIDriver carrying TypeMeta and identity only.
func CreateCSIDriver(name string) *storagev1.CSIDriver {
	return Create[storagev1.CSIDriver](name, "")
}

// CreateCSINode returns a cluster-scoped storage.k8s.io/v1 CSINode carrying TypeMeta and identity only.
func CreateCSINode(name string) *storagev1.CSINode {
	return Create[storagev1.CSINode](name, "")
}

// CreateCSIStorageCapacity returns a storage.k8s.io/v1 CSIStorageCapacity carrying TypeMeta and identity only.
func CreateCSIStorageCapacity(name, namespace string) *storagev1.CSIStorageCapacity {
	return Create[storagev1.CSIStorageCapacity](name, namespace)
}

// CreateClusterRole returns a cluster-scoped rbac.authorization.k8s.io/v1 ClusterRole carrying TypeMeta and identity only.
func CreateClusterRole(name string) *rbacv1.ClusterRole {
	return Create[rbacv1.ClusterRole](name, "")
}

// CreateClusterRoleBinding returns a cluster-scoped rbac.authorization.k8s.io/v1 ClusterRoleBinding carrying TypeMeta and identity only.
func CreateClusterRoleBinding(name string) *rbacv1.ClusterRoleBinding {
	return Create[rbacv1.ClusterRoleBinding](name, "")
}

// CreateComponentStatus returns a cluster-scoped v1 ComponentStatus carrying TypeMeta and identity only.
func CreateComponentStatus(name string) *corev1.ComponentStatus {
	return Create[corev1.ComponentStatus](name, "")
}

// CreateConfigMap returns a v1 ConfigMap carrying TypeMeta and identity only.
func CreateConfigMap(name, namespace string) *corev1.ConfigMap {
	return Create[corev1.ConfigMap](name, namespace)
}

// CreateControllerRevision returns a apps/v1 ControllerRevision carrying TypeMeta and identity only.
func CreateControllerRevision(name, namespace string) *appsv1.ControllerRevision {
	return Create[appsv1.ControllerRevision](name, namespace)
}

// CreateCronJob returns a batch/v1 CronJob carrying TypeMeta and identity only.
func CreateCronJob(name, namespace string) *batchv1.CronJob {
	return Create[batchv1.CronJob](name, namespace)
}

// CreateCustomResourceDefinition returns a cluster-scoped apiextensions.k8s.io/v1 CustomResourceDefinition carrying TypeMeta and identity only.
func CreateCustomResourceDefinition(name string) *apiextensionsv1.CustomResourceDefinition {
	return Create[apiextensionsv1.CustomResourceDefinition](name, "")
}

// CreateDaemonSet returns a apps/v1 DaemonSet carrying TypeMeta and identity only.
func CreateDaemonSet(name, namespace string) *appsv1.DaemonSet {
	return Create[appsv1.DaemonSet](name, namespace)
}

// CreateDeployment returns a apps/v1 Deployment carrying TypeMeta and identity only.
func CreateDeployment(name, namespace string) *appsv1.Deployment {
	return Create[appsv1.Deployment](name, namespace)
}

// CreateEndpoints returns a v1 Endpoints carrying TypeMeta and identity only.
func CreateEndpoints(name, namespace string) *corev1.Endpoints {
	return Create[corev1.Endpoints](name, namespace)
}

// CreateEvent returns a v1 Event carrying TypeMeta and identity only.
func CreateEvent(name, namespace string) *corev1.Event {
	return Create[corev1.Event](name, namespace)
}

// CreateEviction returns a policy/v1 Eviction carrying TypeMeta and identity only.
func CreateEviction(name, namespace string) *policyv1.Eviction {
	return Create[policyv1.Eviction](name, namespace)
}

// CreateGRPCRoute returns a gateway.networking.k8s.io/v1 GRPCRoute carrying TypeMeta and identity only.
func CreateGRPCRoute(name, namespace string) *gatewayapiv1.GRPCRoute {
	return Create[gatewayapiv1.GRPCRoute](name, namespace)
}

// CreateGateway returns a gateway.networking.k8s.io/v1 Gateway carrying TypeMeta and identity only.
func CreateGateway(name, namespace string) *gatewayapiv1.Gateway {
	return Create[gatewayapiv1.Gateway](name, namespace)
}

// CreateGatewayClass returns a cluster-scoped gateway.networking.k8s.io/v1 GatewayClass carrying TypeMeta and identity only.
func CreateGatewayClass(name string) *gatewayapiv1.GatewayClass {
	return Create[gatewayapiv1.GatewayClass](name, "")
}

// CreateHTTPRoute returns a gateway.networking.k8s.io/v1 HTTPRoute carrying TypeMeta and identity only.
func CreateHTTPRoute(name, namespace string) *gatewayapiv1.HTTPRoute {
	return Create[gatewayapiv1.HTTPRoute](name, namespace)
}

// CreateHorizontalPodAutoscaler returns a autoscaling/v2 HorizontalPodAutoscaler carrying TypeMeta and identity only.
func CreateHorizontalPodAutoscaler(name, namespace string) *autoscalingv2.HorizontalPodAutoscaler {
	return Create[autoscalingv2.HorizontalPodAutoscaler](name, namespace)
}

// CreateIPAddress returns a cluster-scoped networking.k8s.io/v1 IPAddress carrying TypeMeta and identity only.
func CreateIPAddress(name string) *networkingv1.IPAddress {
	return Create[networkingv1.IPAddress](name, "")
}

// CreateIngress returns a networking.k8s.io/v1 Ingress carrying TypeMeta and identity only.
func CreateIngress(name, namespace string) *networkingv1.Ingress {
	return Create[networkingv1.Ingress](name, namespace)
}

// CreateIngressClass returns a cluster-scoped networking.k8s.io/v1 IngressClass carrying TypeMeta and identity only.
func CreateIngressClass(name string) *networkingv1.IngressClass {
	return Create[networkingv1.IngressClass](name, "")
}

// CreateJob returns a batch/v1 Job carrying TypeMeta and identity only.
func CreateJob(name, namespace string) *batchv1.Job {
	return Create[batchv1.Job](name, namespace)
}

// CreateLimitRange returns a v1 LimitRange carrying TypeMeta and identity only.
func CreateLimitRange(name, namespace string) *corev1.LimitRange {
	return Create[corev1.LimitRange](name, namespace)
}

// CreateListenerSet returns a gateway.networking.k8s.io/v1 ListenerSet carrying TypeMeta and identity only.
func CreateListenerSet(name, namespace string) *gatewayapiv1.ListenerSet {
	return Create[gatewayapiv1.ListenerSet](name, namespace)
}

// CreateNamespace returns a cluster-scoped v1 Namespace carrying TypeMeta and identity only.
func CreateNamespace(name string) *corev1.Namespace {
	return Create[corev1.Namespace](name, "")
}

// CreateNetworkPolicy returns a networking.k8s.io/v1 NetworkPolicy carrying TypeMeta and identity only.
func CreateNetworkPolicy(name, namespace string) *networkingv1.NetworkPolicy {
	return Create[networkingv1.NetworkPolicy](name, namespace)
}

// CreateNode returns a cluster-scoped v1 Node carrying TypeMeta and identity only.
func CreateNode(name string) *corev1.Node {
	return Create[corev1.Node](name, "")
}

// CreatePersistentVolume returns a cluster-scoped v1 PersistentVolume carrying TypeMeta and identity only.
func CreatePersistentVolume(name string) *corev1.PersistentVolume {
	return Create[corev1.PersistentVolume](name, "")
}

// CreatePersistentVolumeClaim returns a v1 PersistentVolumeClaim carrying TypeMeta and identity only.
func CreatePersistentVolumeClaim(name, namespace string) *corev1.PersistentVolumeClaim {
	return Create[corev1.PersistentVolumeClaim](name, namespace)
}

// CreatePod returns a v1 Pod carrying TypeMeta and identity only.
func CreatePod(name, namespace string) *corev1.Pod {
	return Create[corev1.Pod](name, namespace)
}

// CreatePodDisruptionBudget returns a policy/v1 PodDisruptionBudget carrying TypeMeta and identity only.
func CreatePodDisruptionBudget(name, namespace string) *policyv1.PodDisruptionBudget {
	return Create[policyv1.PodDisruptionBudget](name, namespace)
}

// CreatePodTemplate returns a v1 PodTemplate carrying TypeMeta and identity only.
func CreatePodTemplate(name, namespace string) *corev1.PodTemplate {
	return Create[corev1.PodTemplate](name, namespace)
}

// CreateRangeAllocation returns a cluster-scoped v1 RangeAllocation carrying TypeMeta and identity only.
func CreateRangeAllocation(name string) *corev1.RangeAllocation {
	return Create[corev1.RangeAllocation](name, "")
}

// CreateReferenceGrant returns a gateway.networking.k8s.io/v1 ReferenceGrant carrying TypeMeta and identity only.
func CreateReferenceGrant(name, namespace string) *gatewayapiv1.ReferenceGrant {
	return Create[gatewayapiv1.ReferenceGrant](name, namespace)
}

// CreateReplicaSet returns a apps/v1 ReplicaSet carrying TypeMeta and identity only.
func CreateReplicaSet(name, namespace string) *appsv1.ReplicaSet {
	return Create[appsv1.ReplicaSet](name, namespace)
}

// CreateReplicationController returns a v1 ReplicationController carrying TypeMeta and identity only.
func CreateReplicationController(name, namespace string) *corev1.ReplicationController {
	return Create[corev1.ReplicationController](name, namespace)
}

// CreateResourceQuota returns a v1 ResourceQuota carrying TypeMeta and identity only.
func CreateResourceQuota(name, namespace string) *corev1.ResourceQuota {
	return Create[corev1.ResourceQuota](name, namespace)
}

// CreateRole returns a rbac.authorization.k8s.io/v1 Role carrying TypeMeta and identity only.
func CreateRole(name, namespace string) *rbacv1.Role {
	return Create[rbacv1.Role](name, namespace)
}

// CreateRoleBinding returns a rbac.authorization.k8s.io/v1 RoleBinding carrying TypeMeta and identity only.
func CreateRoleBinding(name, namespace string) *rbacv1.RoleBinding {
	return Create[rbacv1.RoleBinding](name, namespace)
}

// CreateSecret returns a v1 Secret carrying TypeMeta and identity only.
func CreateSecret(name, namespace string) *corev1.Secret {
	return Create[corev1.Secret](name, namespace)
}

// CreateService returns a v1 Service carrying TypeMeta and identity only.
func CreateService(name, namespace string) *corev1.Service {
	return Create[corev1.Service](name, namespace)
}

// CreateServiceAccount returns a v1 ServiceAccount carrying TypeMeta and identity only.
func CreateServiceAccount(name, namespace string) *corev1.ServiceAccount {
	return Create[corev1.ServiceAccount](name, namespace)
}

// CreateServiceCIDR returns a cluster-scoped networking.k8s.io/v1 ServiceCIDR carrying TypeMeta and identity only.
func CreateServiceCIDR(name string) *networkingv1.ServiceCIDR {
	return Create[networkingv1.ServiceCIDR](name, "")
}

// CreateStatefulSet returns a apps/v1 StatefulSet carrying TypeMeta and identity only.
func CreateStatefulSet(name, namespace string) *appsv1.StatefulSet {
	return Create[appsv1.StatefulSet](name, namespace)
}

// CreateStorageClass returns a cluster-scoped storage.k8s.io/v1 StorageClass carrying TypeMeta and identity only.
func CreateStorageClass(name string) *storagev1.StorageClass {
	return Create[storagev1.StorageClass](name, "")
}

// CreateTCPRoute returns a gateway.networking.k8s.io/v1 TCPRoute carrying TypeMeta and identity only.
func CreateTCPRoute(name, namespace string) *gatewayapiv1.TCPRoute {
	return Create[gatewayapiv1.TCPRoute](name, namespace)
}

// CreateTLSRoute returns a gateway.networking.k8s.io/v1 TLSRoute carrying TypeMeta and identity only.
func CreateTLSRoute(name, namespace string) *gatewayapiv1.TLSRoute {
	return Create[gatewayapiv1.TLSRoute](name, namespace)
}

// CreateUDPRoute returns a gateway.networking.k8s.io/v1 UDPRoute carrying TypeMeta and identity only.
func CreateUDPRoute(name, namespace string) *gatewayapiv1.UDPRoute {
	return Create[gatewayapiv1.UDPRoute](name, namespace)
}

// CreateVolumeAttachment returns a cluster-scoped storage.k8s.io/v1 VolumeAttachment carrying TypeMeta and identity only.
func CreateVolumeAttachment(name string) *storagev1.VolumeAttachment {
	return Create[storagev1.VolumeAttachment](name, "")
}

// CreateVolumeAttributesClass returns a cluster-scoped storage.k8s.io/v1 VolumeAttributesClass carrying TypeMeta and identity only.
func CreateVolumeAttributesClass(name string) *storagev1.VolumeAttributesClass {
	return Create[storagev1.VolumeAttributesClass](name, "")
}
