// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package kubernetes

import (
	"testing"

	"sigs.k8s.io/controller-runtime/pkg/client"
)

func TestGeneratedConstructors(t *testing.T) {
	cases := []struct {
		kind       string
		namespaced bool
		obj        client.Object
	}{
		{"BackendTLSPolicy", true, CreateBackendTLSPolicy("name", "ns")},
		{"Binding", true, CreateBinding("name", "ns")},
		{"CSIDriver", false, CreateCSIDriver("name")},
		{"CSINode", false, CreateCSINode("name")},
		{"CSIStorageCapacity", true, CreateCSIStorageCapacity("name", "ns")},
		{"ClusterRole", false, CreateClusterRole("name")},
		{"ClusterRoleBinding", false, CreateClusterRoleBinding("name")},
		{"ComponentStatus", false, CreateComponentStatus("name")},
		{"ConfigMap", true, CreateConfigMap("name", "ns")},
		{"ControllerRevision", true, CreateControllerRevision("name", "ns")},
		{"CronJob", true, CreateCronJob("name", "ns")},
		{"CustomResourceDefinition", false, CreateCustomResourceDefinition("name")},
		{"DaemonSet", true, CreateDaemonSet("name", "ns")},
		{"Deployment", true, CreateDeployment("name", "ns")},
		{"Endpoints", true, CreateEndpoints("name", "ns")},
		{"Event", true, CreateEvent("name", "ns")},
		{"Eviction", true, CreateEviction("name", "ns")},
		{"GRPCRoute", true, CreateGRPCRoute("name", "ns")},
		{"Gateway", true, CreateGateway("name", "ns")},
		{"GatewayClass", false, CreateGatewayClass("name")},
		{"HTTPRoute", true, CreateHTTPRoute("name", "ns")},
		{"HorizontalPodAutoscaler", true, CreateHorizontalPodAutoscaler("name", "ns")},
		{"IPAddress", false, CreateIPAddress("name")},
		{"Ingress", true, CreateIngress("name", "ns")},
		{"IngressClass", false, CreateIngressClass("name")},
		{"Job", true, CreateJob("name", "ns")},
		{"LimitRange", true, CreateLimitRange("name", "ns")},
		{"ListenerSet", true, CreateListenerSet("name", "ns")},
		{"Namespace", false, CreateNamespace("name")},
		{"NetworkPolicy", true, CreateNetworkPolicy("name", "ns")},
		{"Node", false, CreateNode("name")},
		{"PersistentVolume", false, CreatePersistentVolume("name")},
		{"PersistentVolumeClaim", true, CreatePersistentVolumeClaim("name", "ns")},
		{"Pod", true, CreatePod("name", "ns")},
		{"PodDisruptionBudget", true, CreatePodDisruptionBudget("name", "ns")},
		{"PodTemplate", true, CreatePodTemplate("name", "ns")},
		{"RangeAllocation", false, CreateRangeAllocation("name")},
		{"ReferenceGrant", true, CreateReferenceGrant("name", "ns")},
		{"ReplicaSet", true, CreateReplicaSet("name", "ns")},
		{"ReplicationController", true, CreateReplicationController("name", "ns")},
		{"ResourceQuota", true, CreateResourceQuota("name", "ns")},
		{"Role", true, CreateRole("name", "ns")},
		{"RoleBinding", true, CreateRoleBinding("name", "ns")},
		{"Secret", true, CreateSecret("name", "ns")},
		{"Service", true, CreateService("name", "ns")},
		{"ServiceAccount", true, CreateServiceAccount("name", "ns")},
		{"ServiceCIDR", false, CreateServiceCIDR("name")},
		{"StatefulSet", true, CreateStatefulSet("name", "ns")},
		{"StorageClass", false, CreateStorageClass("name")},
		{"TCPRoute", true, CreateTCPRoute("name", "ns")},
		{"TLSRoute", true, CreateTLSRoute("name", "ns")},
		{"UDPRoute", true, CreateUDPRoute("name", "ns")},
		{"VolumeAttachment", false, CreateVolumeAttachment("name")},
		{"VolumeAttributesClass", false, CreateVolumeAttributesClass("name")},
	}
	for _, c := range cases {
		t.Run(c.kind, func(t *testing.T) {
			if got := c.obj.GetObjectKind().GroupVersionKind().Kind; got != c.kind {
				t.Errorf("kind = %q, want %q", got, c.kind)
			}
			wantNS := ""
			if c.namespaced {
				wantNS = "ns"
			}
			if c.obj.GetName() != "name" || c.obj.GetNamespace() != wantNS {
				t.Errorf("identity = %s/%s, want %s/name", c.obj.GetNamespace(), c.obj.GetName(), wantNS)
			}
		})
	}
}
