# Production configuration overrides
deployment.${app.name}.spec.template.spec.containers.0.resources.requests.memory: "1Gi"
deployment.${app.name}.spec.template.spec.containers.0.resources.requests.cpu: "1000m"
deployment.${app.name}.spec.template.spec.containers.0.resources.limits.memory: "4Gi"
deployment.${app.name}.spec.template.spec.containers.0.resources.limits.cpu: "4000m"

# Production storage
persistentvolumeclaim.${app.name}.spec.resources.requests.storage: "500Gi"