// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package cilium

import (
	ciliumiov2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"

	"github.com/go-kure/kure/pkg/kubernetes"
)

// CreateCiliumBGPAdvertisement returns a cluster-scoped cilium.io/v2 CiliumBGPAdvertisement carrying TypeMeta and identity only.
func CreateCiliumBGPAdvertisement(name string) *ciliumiov2.CiliumBGPAdvertisement {
	return kubernetes.Create[ciliumiov2.CiliumBGPAdvertisement](name, "")
}

// CreateCiliumBGPClusterConfig returns a cluster-scoped cilium.io/v2 CiliumBGPClusterConfig carrying TypeMeta and identity only.
func CreateCiliumBGPClusterConfig(name string) *ciliumiov2.CiliumBGPClusterConfig {
	return kubernetes.Create[ciliumiov2.CiliumBGPClusterConfig](name, "")
}

// CreateCiliumBGPNodeConfig returns a cluster-scoped cilium.io/v2 CiliumBGPNodeConfig carrying TypeMeta and identity only.
func CreateCiliumBGPNodeConfig(name string) *ciliumiov2.CiliumBGPNodeConfig {
	return kubernetes.Create[ciliumiov2.CiliumBGPNodeConfig](name, "")
}

// CreateCiliumBGPNodeConfigOverride returns a cluster-scoped cilium.io/v2 CiliumBGPNodeConfigOverride carrying TypeMeta and identity only.
func CreateCiliumBGPNodeConfigOverride(name string) *ciliumiov2.CiliumBGPNodeConfigOverride {
	return kubernetes.Create[ciliumiov2.CiliumBGPNodeConfigOverride](name, "")
}

// CreateCiliumBGPPeerConfig returns a cluster-scoped cilium.io/v2 CiliumBGPPeerConfig carrying TypeMeta and identity only.
func CreateCiliumBGPPeerConfig(name string) *ciliumiov2.CiliumBGPPeerConfig {
	return kubernetes.Create[ciliumiov2.CiliumBGPPeerConfig](name, "")
}

// CreateCiliumCIDRGroup returns a cluster-scoped cilium.io/v2 CiliumCIDRGroup carrying TypeMeta and identity only.
func CreateCiliumCIDRGroup(name string) *ciliumiov2.CiliumCIDRGroup {
	return kubernetes.Create[ciliumiov2.CiliumCIDRGroup](name, "")
}

// CreateCiliumClusterwideEnvoyConfig returns a cluster-scoped cilium.io/v2 CiliumClusterwideEnvoyConfig carrying TypeMeta and identity only.
func CreateCiliumClusterwideEnvoyConfig(name string) *ciliumiov2.CiliumClusterwideEnvoyConfig {
	return kubernetes.Create[ciliumiov2.CiliumClusterwideEnvoyConfig](name, "")
}

// CreateCiliumClusterwideNetworkPolicy returns a cluster-scoped cilium.io/v2 CiliumClusterwideNetworkPolicy carrying TypeMeta and identity only.
func CreateCiliumClusterwideNetworkPolicy(name string) *ciliumiov2.CiliumClusterwideNetworkPolicy {
	return kubernetes.Create[ciliumiov2.CiliumClusterwideNetworkPolicy](name, "")
}

// CreateCiliumEgressGatewayPolicy returns a cluster-scoped cilium.io/v2 CiliumEgressGatewayPolicy carrying TypeMeta and identity only.
func CreateCiliumEgressGatewayPolicy(name string) *ciliumiov2.CiliumEgressGatewayPolicy {
	return kubernetes.Create[ciliumiov2.CiliumEgressGatewayPolicy](name, "")
}

// CreateCiliumEndpoint returns a cilium.io/v2 CiliumEndpoint carrying TypeMeta and identity only.
func CreateCiliumEndpoint(name, namespace string) *ciliumiov2.CiliumEndpoint {
	return kubernetes.Create[ciliumiov2.CiliumEndpoint](name, namespace)
}

// CreateCiliumEnvoyConfig returns a cilium.io/v2 CiliumEnvoyConfig carrying TypeMeta and identity only.
func CreateCiliumEnvoyConfig(name, namespace string) *ciliumiov2.CiliumEnvoyConfig {
	return kubernetes.Create[ciliumiov2.CiliumEnvoyConfig](name, namespace)
}

// CreateCiliumIdentity returns a cluster-scoped cilium.io/v2 CiliumIdentity carrying TypeMeta and identity only.
func CreateCiliumIdentity(name string) *ciliumiov2.CiliumIdentity {
	return kubernetes.Create[ciliumiov2.CiliumIdentity](name, "")
}

// CreateCiliumLoadBalancerIPPool returns a cluster-scoped cilium.io/v2 CiliumLoadBalancerIPPool carrying TypeMeta and identity only.
func CreateCiliumLoadBalancerIPPool(name string) *ciliumiov2.CiliumLoadBalancerIPPool {
	return kubernetes.Create[ciliumiov2.CiliumLoadBalancerIPPool](name, "")
}

// CreateCiliumLocalRedirectPolicy returns a cilium.io/v2 CiliumLocalRedirectPolicy carrying TypeMeta and identity only.
func CreateCiliumLocalRedirectPolicy(name, namespace string) *ciliumiov2.CiliumLocalRedirectPolicy {
	return kubernetes.Create[ciliumiov2.CiliumLocalRedirectPolicy](name, namespace)
}

// CreateCiliumNetworkPolicy returns a cilium.io/v2 CiliumNetworkPolicy carrying TypeMeta and identity only.
func CreateCiliumNetworkPolicy(name, namespace string) *ciliumiov2.CiliumNetworkPolicy {
	return kubernetes.Create[ciliumiov2.CiliumNetworkPolicy](name, namespace)
}

// CreateCiliumNode returns a cluster-scoped cilium.io/v2 CiliumNode carrying TypeMeta and identity only.
func CreateCiliumNode(name string) *ciliumiov2.CiliumNode {
	return kubernetes.Create[ciliumiov2.CiliumNode](name, "")
}

// CreateCiliumNodeConfig returns a cilium.io/v2 CiliumNodeConfig carrying TypeMeta and identity only.
func CreateCiliumNodeConfig(name, namespace string) *ciliumiov2.CiliumNodeConfig {
	return kubernetes.Create[ciliumiov2.CiliumNodeConfig](name, namespace)
}
