// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package cilium

import (
	"testing"

	"sigs.k8s.io/controller-runtime/pkg/client"
)

func TestGeneratedConstructors(t *testing.T) {
	cases := []struct {
		kind       string
		namespaced bool
		obj        client.Object
	}{
		{"CiliumBGPAdvertisement", false, CreateCiliumBGPAdvertisement("name")},
		{"CiliumBGPClusterConfig", false, CreateCiliumBGPClusterConfig("name")},
		{"CiliumBGPNodeConfig", false, CreateCiliumBGPNodeConfig("name")},
		{"CiliumBGPNodeConfigOverride", false, CreateCiliumBGPNodeConfigOverride("name")},
		{"CiliumBGPPeerConfig", false, CreateCiliumBGPPeerConfig("name")},
		{"CiliumCIDRGroup", false, CreateCiliumCIDRGroup("name")},
		{"CiliumClusterwideEnvoyConfig", false, CreateCiliumClusterwideEnvoyConfig("name")},
		{"CiliumClusterwideNetworkPolicy", false, CreateCiliumClusterwideNetworkPolicy("name")},
		{"CiliumEgressGatewayPolicy", false, CreateCiliumEgressGatewayPolicy("name")},
		{"CiliumEndpoint", true, CreateCiliumEndpoint("name", "ns")},
		{"CiliumEnvoyConfig", true, CreateCiliumEnvoyConfig("name", "ns")},
		{"CiliumIdentity", false, CreateCiliumIdentity("name")},
		{"CiliumLoadBalancerIPPool", false, CreateCiliumLoadBalancerIPPool("name")},
		{"CiliumLocalRedirectPolicy", true, CreateCiliumLocalRedirectPolicy("name", "ns")},
		{"CiliumNetworkPolicy", true, CreateCiliumNetworkPolicy("name", "ns")},
		{"CiliumNode", false, CreateCiliumNode("name")},
		{"CiliumNodeConfig", true, CreateCiliumNodeConfig("name", "ns")},
	}
	for _, c := range cases {
		t.Run(c.kind, func(t *testing.T) {
			if got := c.obj.GetObjectKind().GroupVersionKind().Kind; got != c.kind {
				t.Errorf("kind = %q, want %q", got, c.kind)
			}
			wantNS := ""
			if c.namespaced {
				wantNS = "ns"
			}
			if c.obj.GetName() != "name" || c.obj.GetNamespace() != wantNS {
				t.Errorf("identity = %s/%s, want %s/name", c.obj.GetNamespace(), c.obj.GetName(), wantNS)
			}
		})
	}
}
