name: Bug Report
description: Report a bug in Kure
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Kure Version
      placeholder: e.g. v0.1.0 or commit hash
    validations:
      required: true
  - type: input
    id: go-version
    attributes:
      label: Go Version
      placeholder: e.g. 1.24.11
