// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package externalsecrets

import (
	externalsecretsv1 "github.com/external-secrets/external-secrets/apis/externalsecrets/v1"

	"github.com/go-kure/kure/pkg/kubernetes"
)

// CreateClusterExternalSecret returns a cluster-scoped external-secrets.io/v1 ClusterExternalSecret carrying TypeMeta and identity only.
func CreateClusterExternalSecret(name string) *externalsecretsv1.ClusterExternalSecret {
	return kubernetes.Create[externalsecretsv1.ClusterExternalSecret](name, "")
}

// CreateClusterSecretStore returns a cluster-scoped external-secrets.io/v1 ClusterSecretStore carrying TypeMeta and identity only.
func CreateClusterSecretStore(name string) *externalsecretsv1.ClusterSecretStore {
	return kubernetes.Create[externalsecretsv1.ClusterSecretStore](name, "")
}

// CreateExternalSecret returns a external-secrets.io/v1 ExternalSecret carrying TypeMeta and identity only.
func CreateExternalSecret(name, namespace string) *externalsecretsv1.ExternalSecret {
	return kubernetes.Create[externalsecretsv1.ExternalSecret](name, namespace)
}

// CreateSecretStore returns a external-secrets.io/v1 SecretStore carrying TypeMeta and identity only.
func CreateSecretStore(name, namespace string) *externalsecretsv1.SecretStore {
	return kubernetes.Create[externalsecretsv1.SecretStore](name, namespace)
}
