// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package fluxcd

import (
	"testing"

	"sigs.k8s.io/controller-runtime/pkg/client"
)

func TestGeneratedConstructors(t *testing.T) {
	cases := []struct {
		kind       string
		namespaced bool
		obj        client.Object
	}{
		{"Alert", true, CreateAlert("name", "ns")},
		{"ArtifactGenerator", true, CreateArtifactGenerator("name", "ns")},
		{"Bucket", true, CreateBucket("name", "ns")},
		{"ExternalArtifact", true, CreateExternalArtifact("name", "ns")},
		{"FluxInstance", true, CreateFluxInstance("name", "ns")},
		{"FluxReport", true, CreateFluxReport("name", "ns")},
		{"GitRepository", true, CreateGitRepository("name", "ns")},
		{"HelmChart", true, CreateHelmChart("name", "ns")},
		{"HelmRelease", true, CreateHelmRelease("name", "ns")},
		{"HelmRepository", true, CreateHelmRepository("name", "ns")},
		{"ImageUpdateAutomation", true, CreateImageUpdateAutomation("name", "ns")},
		{"Kustomization", true, CreateKustomization("name", "ns")},
		{"OCIRepository", true, CreateOCIRepository("name", "ns")},
		{"Provider", true, CreateProvider("name", "ns")},
		{"Receiver", true, CreateReceiver("name", "ns")},
		{"ResourceSet", true, CreateResourceSet("name", "ns")},
		{"ResourceSetInputProvider", true, CreateResourceSetInputProvider("name", "ns")},
	}
	for _, c := range cases {
		t.Run(c.kind, func(t *testing.T) {
			if got := c.obj.GetObjectKind().GroupVersionKind().Kind; got != c.kind {
				t.Errorf("kind = %q, want %q", got, c.kind)
			}
			wantNS := ""
			if c.namespaced {
				wantNS = "ns"
			}
			if c.obj.GetName() != "name" || c.obj.GetNamespace() != wantNS {
				t.Errorf("identity = %s/%s, want %s/name", c.obj.GetNamespace(), c.obj.GetName(), wantNS)
			}
		})
	}
}
