// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package fluxcd

import (
	fluxoperatorv1 "github.com/controlplaneio-fluxcd/flux-operator/api/v1"
	helmcontrollerv2 "github.com/fluxcd/helm-controller/api/v2"
	imageautomationcontrollerv1 "github.com/fluxcd/image-automation-controller/api/v1"
	kustomizecontrollerv1 "github.com/fluxcd/kustomize-controller/api/v1"
	notificationcontrollerv1 "github.com/fluxcd/notification-controller/api/v1"
	notificationcontrollerv1beta3 "github.com/fluxcd/notification-controller/api/v1beta3"
	sourcecontrollerv1 "github.com/fluxcd/source-controller/api/v1"
	sourcewatcherv2v1beta1 "github.com/fluxcd/source-watcher/api/v2/v1beta1"

	"github.com/go-kure/kure/pkg/kubernetes"
)

// CreateAlert returns a notification.toolkit.fluxcd.io/v1beta3 Alert carrying TypeMeta and identity only.
func CreateAlert(name, namespace string) *notificationcontrollerv1beta3.Alert {
	return kubernetes.Create[notificationcontrollerv1beta3.Alert](name, namespace)
}

// CreateArtifactGenerator returns a source.extensions.fluxcd.io/v1beta1 ArtifactGenerator carrying TypeMeta and identity only.
func CreateArtifactGenerator(name, namespace string) *sourcewatcherv2v1beta1.ArtifactGenerator {
	return kubernetes.Create[sourcewatcherv2v1beta1.ArtifactGenerator](name, namespace)
}

// CreateBucket returns a source.toolkit.fluxcd.io/v1 Bucket carrying TypeMeta and identity only.
func CreateBucket(name, namespace string) *sourcecontrollerv1.Bucket {
	return kubernetes.Create[sourcecontrollerv1.Bucket](name, namespace)
}

// CreateExternalArtifact returns a source.toolkit.fluxcd.io/v1 ExternalArtifact carrying TypeMeta and identity only.
func CreateExternalArtifact(name, namespace string) *sourcecontrollerv1.ExternalArtifact {
	return kubernetes.Create[sourcecontrollerv1.ExternalArtifact](name, namespace)
}

// CreateFluxInstance returns a fluxcd.controlplane.io/v1 FluxInstance carrying TypeMeta and identity only.
func CreateFluxInstance(name, namespace string) *fluxoperatorv1.FluxInstance {
	return kubernetes.Create[fluxoperatorv1.FluxInstance](name, namespace)
}

// CreateFluxReport returns a fluxcd.controlplane.io/v1 FluxReport carrying TypeMeta and identity only.
func CreateFluxReport(name, namespace string) *fluxoperatorv1.FluxReport {
	return kubernetes.Create[fluxoperatorv1.FluxReport](name, namespace)
}

// CreateGitRepository returns a source.toolkit.fluxcd.io/v1 GitRepository carrying TypeMeta and identity only.
func CreateGitRepository(name, namespace string) *sourcecontrollerv1.GitRepository {
	return kubernetes.Create[sourcecontrollerv1.GitRepository](name, namespace)
}

// CreateHelmChart returns a source.toolkit.fluxcd.io/v1 HelmChart carrying TypeMeta and identity only.
func CreateHelmChart(name, namespace string) *sourcecontrollerv1.HelmChart {
	return kubernetes.Create[sourcecontrollerv1.HelmChart](name, namespace)
}

// CreateHelmRelease returns a helm.toolkit.fluxcd.io/v2 HelmRelease carrying TypeMeta and identity only.
func CreateHelmRelease(name, namespace string) *helmcontrollerv2.HelmRelease {
	return kubernetes.Create[helmcontrollerv2.HelmRelease](name, namespace)
}

// CreateHelmRepository returns a source.toolkit.fluxcd.io/v1 HelmRepository carrying TypeMeta and identity only.
func CreateHelmRepository(name, namespace string) *sourcecontrollerv1.HelmRepository {
	return kubernetes.Create[sourcecontrollerv1.HelmRepository](name, namespace)
}

// CreateImageUpdateAutomation returns a image.toolkit.fluxcd.io/v1 ImageUpdateAutomation carrying TypeMeta and identity only.
func CreateImageUpdateAutomation(name, namespace string) *imageautomationcontrollerv1.ImageUpdateAutomation {
	return kubernetes.Create[imageautomationcontrollerv1.ImageUpdateAutomation](name, namespace)
}

// CreateKustomization returns a kustomize.toolkit.fluxcd.io/v1 Kustomization carrying TypeMeta and identity only.
func CreateKustomization(name, namespace string) *kustomizecontrollerv1.Kustomization {
	return kubernetes.Create[kustomizecontrollerv1.Kustomization](name, namespace)
}

// CreateOCIRepository returns a source.toolkit.fluxcd.io/v1 OCIRepository carrying TypeMeta and identity only.
func CreateOCIRepository(name, namespace string) *sourcecontrollerv1.OCIRepository {
	return kubernetes.Create[sourcecontrollerv1.OCIRepository](name, namespace)
}

// CreateProvider returns a notification.toolkit.fluxcd.io/v1beta3 Provider carrying TypeMeta and identity only.
func CreateProvider(name, namespace string) *notificationcontrollerv1beta3.Provider {
	return kubernetes.Create[notificationcontrollerv1beta3.Provider](name, namespace)
}

// CreateReceiver returns a notification.toolkit.fluxcd.io/v1 Receiver carrying TypeMeta and identity only.
func CreateReceiver(name, namespace string) *notificationcontrollerv1.Receiver {
	return kubernetes.Create[notificationcontrollerv1.Receiver](name, namespace)
}

// CreateResourceSet returns a fluxcd.controlplane.io/v1 ResourceSet carrying TypeMeta and identity only.
func CreateResourceSet(name, namespace string) *fluxoperatorv1.ResourceSet {
	return kubernetes.Create[fluxoperatorv1.ResourceSet](name, namespace)
}

// CreateResourceSetInputProvider returns a fluxcd.controlplane.io/v1 ResourceSetInputProvider carrying TypeMeta and identity only.
func CreateResourceSetInputProvider(name, namespace string) *fluxoperatorv1.ResourceSetInputProvider {
	return kubernetes.Create[fluxoperatorv1.ResourceSetInputProvider](name, namespace)
}
