// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package prometheus

import (
	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"

	"github.com/go-kure/kure/pkg/kubernetes"
)

// CreateAlertmanager returns a monitoring.coreos.com/v1 Alertmanager carrying TypeMeta and identity only.
func CreateAlertmanager(name, namespace string) *monitoringv1.Alertmanager {
	return kubernetes.Create[monitoringv1.Alertmanager](name, namespace)
}

// CreatePodMonitor returns a monitoring.coreos.com/v1 PodMonitor carrying TypeMeta and identity only.
func CreatePodMonitor(name, namespace string) *monitoringv1.PodMonitor {
	return kubernetes.Create[monitoringv1.PodMonitor](name, namespace)
}

// CreateProbe returns a monitoring.coreos.com/v1 Probe carrying TypeMeta and identity only.
func CreateProbe(name, namespace string) *monitoringv1.Probe {
	return kubernetes.Create[monitoringv1.Probe](name, namespace)
}

// CreatePrometheus returns a monitoring.coreos.com/v1 Prometheus carrying TypeMeta and identity only.
func CreatePrometheus(name, namespace string) *monitoringv1.Prometheus {
	return kubernetes.Create[monitoringv1.Prometheus](name, namespace)
}

// CreatePrometheusRule returns a monitoring.coreos.com/v1 PrometheusRule carrying TypeMeta and identity only.
func CreatePrometheusRule(name, namespace string) *monitoringv1.PrometheusRule {
	return kubernetes.Create[monitoringv1.PrometheusRule](name, namespace)
}

// CreateServiceMonitor returns a monitoring.coreos.com/v1 ServiceMonitor carrying TypeMeta and identity only.
func CreateServiceMonitor(name, namespace string) *monitoringv1.ServiceMonitor {
	return kubernetes.Create[monitoringv1.ServiceMonitor](name, namespace)
}

// CreateThanosRuler returns a monitoring.coreos.com/v1 ThanosRuler carrying TypeMeta and identity only.
func CreateThanosRuler(name, namespace string) *monitoringv1.ThanosRuler {
	return kubernetes.Create[monitoringv1.ThanosRuler](name, namespace)
}
