// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package prometheus

import (
	"testing"

	"sigs.k8s.io/controller-runtime/pkg/client"
)

func TestGeneratedConstructors(t *testing.T) {
	cases := []struct {
		kind       string
		namespaced bool
		obj        client.Object
	}{
		{"Alertmanager", true, CreateAlertmanager("name", "ns")},
		{"PodMonitor", true, CreatePodMonitor("name", "ns")},
		{"Probe", true, CreateProbe("name", "ns")},
		{"Prometheus", true, CreatePrometheus("name", "ns")},
		{"PrometheusRule", true, CreatePrometheusRule("name", "ns")},
		{"ServiceMonitor", true, CreateServiceMonitor("name", "ns")},
		{"ThanosRuler", true, CreateThanosRuler("name", "ns")},
	}
	for _, c := range cases {
		t.Run(c.kind, func(t *testing.T) {
			if got := c.obj.GetObjectKind().GroupVersionKind().Kind; got != c.kind {
				t.Errorf("kind = %q, want %q", got, c.kind)
			}
			wantNS := ""
			if c.namespaced {
				wantNS = "ns"
			}
			if c.obj.GetName() != "name" || c.obj.GetNamespace() != wantNS {
				t.Errorf("identity = %s/%s, want %s/name", c.obj.GetNamespace(), c.obj.GetName(), wantNS)
			}
		})
	}
}
