apiVersion: generators.gokure.dev/v1alpha1
kind: AppWorkload
metadata:
  name: nginx-demo
  namespace: web
spec:
  workload: Deployment
  replicas: 3
  labels:
    app: nginx
    tier: frontend
  containers:
    - name: nginx
      image: nginx:1.21-alpine
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
      volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: nginx-config
  services:
    - name: nginx-service
      type: LoadBalancer
      ports:
        - name: http
          port: 80
          targetPort: http
          protocol: TCP
  ingress:
    host: nginx.example.com
    serviceName: nginx-service
    servicePortName: http