apiVersion: generators.gokure.dev/v1alpha1
kind: FluxHelm
metadata:
  name: podinfo
  namespace: apps
spec:
  chart:
    name: podinfo
    version: "6.*"
  source:
    type: OCIRepository
    ociUrl: oci://ghcr.io/stefanprodan/charts/podinfo
    interval: 5m
  values:
    replicaCount: 2
    service:
      type: ClusterIP
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: podinfo.example.com
          paths:
            - path: /
              pathType: Prefix
  release:
    createNamespace: true
  interval: 10m
  suspend: false