package fluxcd_test

import (
	"slices"
	"strings"
	"testing"

	kustv1 "github.com/fluxcd/kustomize-controller/api/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/go-kure/kure/pkg/stack"
	fluxstack "github.com/go-kure/kure/pkg/stack/fluxcd"
	"github.com/go-kure/kure/pkg/stack/layout"
)

// TestFluxWorkflow_BundleNameOverLimit: the 63-character limit is Flux's, so
// cluster validation accepts a longer bundle name and the Flux workflow
// refuses it where it builds the bundle's Kustomization. Every entry point
// that generates from a cluster or a layout refuses, for a node's bundle and
// for an umbrella descendant, names the bundle by its path, and returns
// nothing to write.
func TestFluxWorkflow_BundleNameOverLimit(t *testing.T) {
	long := strings.Repeat("a", stack.KustomizationNameMaxLength+1)
	bundle := func(name string, children ...*stack.Bundle) *stack.Bundle {
		return &stack.Bundle{
			Name:         name,
			SourceRef:    testSR(),
			Children:     children,
			Applications: []*stack.Application{fakeUmbrellaApp(name+"-app", "cm-"+name)},
		}
	}
	clusters := []struct {
		name     string
		bundle   func() *stack.Bundle
		wantPath string
	}{
		{"node bundle", func() *stack.Bundle { return bundle(long) }, "'" + long + "'"},
		{
			"umbrella child",
			func() *stack.Bundle { return bundle("platform", bundle("infra"), bundle(long)) },
			"'platform/" + long + "'",
		},
		{
			"umbrella grandchild",
			func() *stack.Bundle { return bundle("platform", bundle("infra", bundle(long))) },
			"'platform/infra/" + long + "'",
		},
	}
	cluster := func(b *stack.Bundle) *stack.Cluster {
		node := &stack.Node{Name: "apps", Bundle: b}
		root := &stack.Node{Name: "demo", Children: []*stack.Node{node}}
		node.SetParent(root)
		return &stack.Cluster{Name: "demo", Node: root}
	}
	entryPoints := []struct {
		name string
		run  func(t *testing.T, c *stack.Cluster) (any, error)
	}{
		{"GenerateFromCluster", func(_ *testing.T, c *stack.Cluster) (any, error) {
			objs, err := fluxstack.NewResourceGenerator().GenerateFromCluster(c, layout.DefaultLayoutRules())
			if objs == nil {
				return nil, err
			}
			return objs, err
		}},
		{"GenerateFromLayout", func(t *testing.T, c *stack.Cluster) (any, error) {
			ml, err := layout.WalkCluster(c, layout.DefaultLayoutRules())
			if err != nil {
				t.Fatalf("WalkCluster refused a name only Flux limits: %v", err)
			}
			objs, err := fluxstack.NewResourceGenerator().GenerateFromLayout(ml, c)
			if objs == nil {
				return nil, err
			}
			return objs, err
		}},
	}
	for _, p := range []layout.FluxPlacement{layout.FluxSeparate, layout.FluxIntegratedPerBundle, layout.FluxIntegratedPerLayout} {
		entryPoints = append(entryPoints, struct {
			name string
			run  func(t *testing.T, c *stack.Cluster) (any, error)
		}{"CreateLayoutWithResources " + string(p), func(_ *testing.T, c *stack.Cluster) (any, error) {
			ml, err := fluxstack.NewLayoutIntegrator(fluxstack.NewResourceGenerator()).CreateLayoutWithResources(c, layout.LayoutRules{
				BundleGrouping:      layout.GroupFlat,
				ApplicationGrouping: layout.GroupFlat,
				FluxPlacement:       p,
			})
			if ml == nil {
				return nil, err
			}
			return ml, err
		}})
	}

	for _, tc := range clusters {
		for _, ep := range entryPoints {
			t.Run(tc.name+"/"+ep.name, func(t *testing.T) {
				c := cluster(tc.bundle())
				if err := stack.ValidateCluster(c); err != nil {
					t.Fatalf("ValidateCluster() = %v, want nil: the limit is not the model's", err)
				}
				got, err := ep.run(t, c)
				if err == nil {
					t.Fatal("generated without an error, want the over-limit refusal")
				}
				if got != nil {
					t.Errorf("returned %v next to the error, want nothing to write", got)
				}
				for _, want := range []string{tc.wantPath, "at most 63 characters"} {
					if !strings.Contains(err.Error(), want) {
						t.Errorf("error = %v, want it to contain %q", err, want)
					}
				}
			})
		}
	}
}

// fluxEntryPoints are the entry points that generate Flux Kustomizations from
// a cluster under rules: the generator from the cluster, the generator from a
// walked layout, and the integrator. Each returns the Kustomizations it
// generated by name, or nil next to an error.
func fluxEntryPoints(rules layout.LayoutRules) []struct {
	name string
	run  func(t *testing.T, c *stack.Cluster) (map[string]*kustv1.Kustomization, error)
} {
	byName := func(objs []client.Object) map[string]*kustv1.Kustomization {
		out := map[string]*kustv1.Kustomization{}
		for _, o := range objs {
			if k, ok := o.(*kustv1.Kustomization); ok {
				out[k.Name] = k
			}
		}
		return out
	}
	return []struct {
		name string
		run  func(t *testing.T, c *stack.Cluster) (map[string]*kustv1.Kustomization, error)
	}{
		{"GenerateFromCluster", func(_ *testing.T, c *stack.Cluster) (map[string]*kustv1.Kustomization, error) {
			objs, err := fluxstack.NewResourceGenerator().GenerateFromCluster(c, rules)
			if err != nil {
				return nil, err
			}
			return byName(objs), nil
		}},
		{"GenerateFromLayout", func(t *testing.T, c *stack.Cluster) (map[string]*kustv1.Kustomization, error) {
			ml, err := layout.WalkCluster(c, rules)
			if err != nil {
				t.Fatalf("WalkCluster refused a name only Flux limits: %v", err)
			}
			objs, err := fluxstack.NewResourceGenerator().GenerateFromLayout(ml, c)
			if err != nil {
				return nil, err
			}
			return byName(objs), nil
		}},
		{"CreateLayoutWithResources", func(_ *testing.T, c *stack.Cluster) (map[string]*kustv1.Kustomization, error) {
			integrated := rules
			integrated.FluxPlacement = layout.FluxIntegratedPerBundle
			ml, err := fluxstack.NewLayoutIntegrator(fluxstack.NewResourceGenerator()).CreateLayoutWithResources(c, integrated)
			if err != nil {
				return nil, err
			}
			var objs []client.Object
			var collect func(l *layout.ManifestLayout)
			collect = func(l *layout.ManifestLayout) {
				objs = append(objs, l.Resources...)
				for _, child := range l.Children {
					collect(child)
				}
			}
			collect(ml)
			return byName(objs), nil
		}},
	}
}

// TestFluxWorkflow_KustomizationNameOverLimit: the 63-character limit is on
// the name the Kustomization gets, the bundle's name in effect. A bundle whose
// KustomizationName is over the limit is refused by every entry point, named
// by its path with the field that holds the name; a bundle whose Name is over
// the limit and whose KustomizationName is not generates, because the Name is
// then no Kustomization's.
func TestFluxWorkflow_KustomizationNameOverLimit(t *testing.T) {
	long := strings.Repeat("a", stack.KustomizationNameMaxLength+1)
	cluster := func(b *stack.Bundle) *stack.Cluster {
		b.SourceRef = testSR()
		b.Applications = []*stack.Application{fakeUmbrellaApp("app", "cm")}
		node := &stack.Node{Name: "apps", Bundle: b}
		root := &stack.Node{Name: "demo", Children: []*stack.Node{node}}
		node.SetParent(root)
		return &stack.Cluster{Name: "demo", Node: root}
	}
	for _, ep := range fluxEntryPoints(layout.DefaultLayoutRules()) {
		t.Run(ep.name+"/KustomizationName over the limit", func(t *testing.T) {
			c := cluster(&stack.Bundle{Name: "web", KustomizationName: long})
			if err := stack.ValidateCluster(c); err != nil {
				t.Fatalf("ValidateCluster() = %v, want nil: the limit is not the model's", err)
			}
			got, err := ep.run(t, c)
			if err == nil {
				t.Fatal("generated without an error, want the over-limit refusal")
			}
			if got != nil {
				t.Errorf("returned %v next to the error, want nothing to write", got)
			}
			for _, want := range []string{"'web'", "field 'kustomizationName'", "at most 63 characters"} {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("error = %v, want it to contain %q", err, want)
				}
			}
		})
		t.Run(ep.name+"/Name over the limit, KustomizationName within it", func(t *testing.T) {
			got, err := ep.run(t, cluster(&stack.Bundle{Name: long, KustomizationName: "web"}))
			if err != nil {
				t.Fatalf("refused a bundle whose Kustomization is named %q: %v", "web", err)
			}
			if got["web"] == nil || len(got) != 1 {
				t.Errorf("Kustomizations = %v, want exactly %q", kustNames(got), "web")
			}
		})
	}

	t.Run("GenerateForBundle/KustomizationName over the limit", func(t *testing.T) {
		objs, err := fluxstack.NewResourceGenerator().GenerateForBundle(
			&stack.Bundle{Name: "web", KustomizationName: long}, "clusters/prod/web")
		if err == nil || objs != nil {
			t.Fatalf("GenerateForBundle() = %v, %v; want the over-limit refusal and nothing to write", objs, err)
		}
		for _, want := range []string{"'web'", "field 'kustomizationName'", "at most 63 characters"} {
			if !strings.Contains(err.Error(), want) {
				t.Errorf("GenerateForBundle() = %v, want it to contain %q", err, want)
			}
		}
	})
	t.Run("GenerateForBundle/Name over the limit, KustomizationName within it", func(t *testing.T) {
		objs, err := fluxstack.NewResourceGenerator().GenerateForBundle(
			&stack.Bundle{Name: long, KustomizationName: "web"}, "clusters/prod/web")
		if err != nil {
			t.Fatalf("GenerateForBundle() refused a bundle whose Kustomization is named %q: %v", "web", err)
		}
		if len(objs) != 1 || objs[0].GetName() != "web" {
			t.Errorf("GenerateForBundle() = %v, want one Kustomization named %q", objs, "web")
		}
	})
	t.Run("GenerateForBundle/reference to a KustomizationName over the limit", func(t *testing.T) {
		for _, b := range []*stack.Bundle{
			{Name: "platform", Children: []*stack.Bundle{{Name: "infra", KustomizationName: long}}},
			{Name: "web", DependsOn: []*stack.Bundle{{Name: "db", KustomizationName: long}}},
		} {
			objs, err := fluxstack.NewResourceGenerator().GenerateForBundle(b, "clusters/prod/"+b.Name)
			if err == nil || objs != nil {
				t.Fatalf("GenerateForBundle(%s) = %v, %v; want the over-limit refusal and nothing to write", b.Name, objs, err)
			}
			for _, want := range []string{"field 'kustomizationName'", "at most 63 characters"} {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("GenerateForBundle(%s) = %v, want it to contain %q", b.Name, err, want)
				}
			}
		}
	})
}

// kustNames lists the names of the generated Kustomizations, sorted.
func kustNames(got map[string]*kustv1.Kustomization) []string {
	names := make([]string, 0, len(got))
	for name := range got {
		names = append(names, name)
	}
	slices.Sort(names)
	return names
}

// TestFluxWorkflow_OverLimitNameThatNamesNoKustomization: under flat node and
// bundle grouping the bundles of a cluster share one directory and so one
// Kustomization, named after the first of them. The limit is checked on that
// name only: the name of a bundle merged into the unit is written nowhere, and
// a dependency on such a bundle from inside the unit is dropped, because the
// unit would depend on itself. The test reads the outcome off the generated
// objects: one Kustomization, named after the first bundle, that refers to no
// other. If the rules stop merging these bundles it fails and says so, instead
// of passing on a tree that no longer holds a merged name.
func TestFluxWorkflow_OverLimitNameThatNamesNoKustomization(t *testing.T) {
	long := strings.Repeat("a", stack.KustomizationNameMaxLength+1)
	flat := layout.DefaultLayoutRules()
	flat.NodeGrouping = layout.GroupFlat
	flat.BundleGrouping = layout.GroupFlat

	bundle := func(name string) *stack.Bundle {
		return &stack.Bundle{
			Name:         name,
			SourceRef:    testSR(),
			Applications: []*stack.Application{fakeUmbrellaApp(name+"-app", "cm-"+name)},
		}
	}
	// first names the unit; the over-long bundle is merged into it, and so is
	// web, which depends on the over-long bundle.
	cluster := func() *stack.Cluster {
		merged := bundle(long)
		web := bundle("web")
		web.DependsOn = []*stack.Bundle{merged}
		root := &stack.Node{Name: "demo", Bundle: bundle("first")}
		for _, n := range []*stack.Node{{Name: "apps", Bundle: merged}, {Name: "web", Bundle: web}} {
			n.SetParent(root)
			root.Children = append(root.Children, n)
		}
		return &stack.Cluster{Name: "demo", Node: root}
	}

	for _, ep := range fluxEntryPoints(flat) {
		t.Run(ep.name, func(t *testing.T) {
			got, err := ep.run(t, cluster())
			if err != nil {
				t.Fatalf("refused a bundle name that names no Kustomization: %v", err)
			}
			if len(got) != 1 || got["first"] == nil {
				t.Fatalf("Kustomizations = %v, want the one unit %q: the rules no longer merge the bundles, so this test proves nothing", kustNames(got), "first")
			}
			unit := got["first"]
			if len(unit.Spec.DependsOn) != 0 {
				t.Errorf("spec.dependsOn = %v, want none: web's dependency on the merged bundle is inside the unit", unit.Spec.DependsOn)
			}
			if len(unit.Spec.HealthChecks) != 0 {
				t.Errorf("spec.healthChecks = %v, want none: no bundle is an umbrella", unit.Spec.HealthChecks)
			}
		})
	}

	// The same bundle first in its directory names the unit, and is refused.
	t.Run("over-long bundle first", func(t *testing.T) {
		for _, ep := range fluxEntryPoints(flat) {
			root := &stack.Node{Name: "demo", Bundle: bundle(long)}
			child := &stack.Node{Name: "apps", Bundle: bundle("second")}
			child.SetParent(root)
			root.Children = []*stack.Node{child}
			got, err := ep.run(t, &stack.Cluster{Name: "demo", Node: root})
			if err == nil || got != nil {
				t.Fatalf("%s = %v, %v; want the over-limit refusal and nothing to write", ep.name, kustNames(got), err)
			}
			for _, want := range []string{"'" + long + "'", "at most 63 characters"} {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("%s: error = %v, want it to contain %q", ep.name, err, want)
				}
			}
		}
	})
}

// TestFluxWorkflow_OverLimitReferenceOutsideTheCluster: a DependsOn bundle that
// is not one of the cluster's bundles gets no Kustomization from this pass, so
// nothing else checks the name the dependency is written with. It is refused
// like the bundle's own, by every entry point, with the referenced bundle's
// name.
func TestFluxWorkflow_OverLimitReferenceOutsideTheCluster(t *testing.T) {
	long := strings.Repeat("a", stack.KustomizationNameMaxLength+1)
	for _, outside := range []*stack.Bundle{{Name: long}, {Name: "db", KustomizationName: long}} {
		for _, ep := range fluxEntryPoints(layout.DefaultLayoutRules()) {
			web := &stack.Bundle{
				Name:         "web",
				SourceRef:    testSR(),
				Applications: []*stack.Application{fakeUmbrellaApp("web-app", "cm-web")},
				DependsOn:    []*stack.Bundle{outside},
			}
			node := &stack.Node{Name: "apps", Bundle: web}
			root := &stack.Node{Name: "demo", Children: []*stack.Node{node}}
			node.SetParent(root)
			c := &stack.Cluster{Name: "demo", Node: root}
			if err := stack.ValidateCluster(c); err != nil {
				t.Fatalf("ValidateCluster() = %v, want nil: the limit is not the model's", err)
			}
			got, err := ep.run(t, c)
			if err == nil || got != nil {
				t.Fatalf("%s = %v, %v; want the over-limit refusal and nothing to write", ep.name, kustNames(got), err)
			}
			for _, want := range []string{"'" + outside.Name + "'", "at most 63 characters"} {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("%s: error = %v, want it to contain %q", ep.name, err, want)
				}
			}
		}
	}
}

// TestGenerateForBundle_NamesUmbrellaChildByPath: GenerateForBundle builds one
// Kustomization and walks no cluster, so the path it reports is the one the
// bundle itself carries. An umbrella child whose parent is known is named
// with it.
func TestGenerateForBundle_NamesUmbrellaChildByPath(t *testing.T) {
	long := strings.Repeat("a", stack.KustomizationNameMaxLength+1)
	child := &stack.Bundle{Name: long}
	umbrella := &stack.Bundle{Name: "platform", Children: []*stack.Bundle{child}}
	umbrella.InitializeUmbrella()

	_, err := fluxstack.NewResourceGenerator().GenerateForBundle(child, "clusters/prod/platform")
	if err == nil {
		t.Fatal("GenerateForBundle() generated, want the over-limit refusal")
	}
	for _, want := range []string{"'platform/" + long + "'", "at most 63 characters"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("GenerateForBundle() = %v, want it to contain %q", err, want)
		}
	}
}

// TestGenerateForBundle_RefusesOverLimitReference: the Kustomization built for
// a bundle also names other bundles' Kustomizations: an umbrella's children as
// health checks, its DependsOn bundles as dependencies. GenerateForBundle
// builds neither of those, so nothing else would check their names: a
// reference to a name Flux cannot reconcile is refused like the bundle's own,
// with the referenced bundle's path, and nothing is returned.
func TestGenerateForBundle_RefusesOverLimitReference(t *testing.T) {
	long := strings.Repeat("a", stack.KustomizationNameMaxLength+1)
	cases := []struct {
		name     string
		bundle   func() *stack.Bundle
		wantPath string
	}{
		{
			"umbrella child",
			func() *stack.Bundle {
				return &stack.Bundle{Name: "platform", Children: []*stack.Bundle{{Name: "infra"}, {Name: long}}}
			},
			"'platform/" + long + "'",
		},
		{
			"dependency",
			func() *stack.Bundle {
				return &stack.Bundle{Name: "web", DependsOn: []*stack.Bundle{{Name: "db"}, {Name: long}}}
			},
			"'" + long + "'",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			b := tc.bundle()
			if err := b.Validate(); err != nil {
				t.Fatalf("Validate() = %v, want nil: the limit is not the model's", err)
			}
			objs, err := fluxstack.NewResourceGenerator().GenerateForBundle(b, "clusters/prod/"+b.Name)
			if err == nil {
				t.Fatal("GenerateForBundle() generated, want the over-limit refusal")
			}
			if objs != nil {
				t.Errorf("GenerateForBundle() returned %v next to the error, want nothing to write", objs)
			}
			for _, want := range []string{tc.wantPath, "at most 63 characters"} {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("GenerateForBundle() = %v, want it to contain %q", err, want)
				}
			}
		})
	}
}

// TestGenerateForBundle_RefusesNilDependency: Bundle.Validate refuses a nil
// DependsOn entry, and GenerateForBundle is reached without it. The generator
// names the bundle and the entry instead of dereferencing it, and returns
// nothing.
func TestGenerateForBundle_RefusesNilDependency(t *testing.T) {
	b := &stack.Bundle{Name: "web", DependsOn: []*stack.Bundle{{Name: "db"}, nil}}
	objs, err := fluxstack.NewResourceGenerator().GenerateForBundle(b, "clusters/prod/web")
	if err == nil {
		t.Fatal("GenerateForBundle() generated, want the nil dependency refused")
	}
	if objs != nil {
		t.Errorf("GenerateForBundle() returned %v next to the error, want nothing to write", objs)
	}
	for _, want := range []string{"'web'", "dependency at index 1 is nil"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("GenerateForBundle() = %v, want it to contain %q", err, want)
		}
	}
}
