// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package certmanager

import (
	acmev1 "github.com/cert-manager/cert-manager/pkg/apis/acme/v1"
	certmanagerv1 "github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1"

	"github.com/go-kure/kure/pkg/kubernetes"
)

// CreateCertificate returns a cert-manager.io/v1 Certificate carrying TypeMeta and identity only.
func CreateCertificate(name, namespace string) *certmanagerv1.Certificate {
	return kubernetes.Create[certmanagerv1.Certificate](name, namespace)
}

// CreateCertificateRequest returns a cert-manager.io/v1 CertificateRequest carrying TypeMeta and identity only.
func CreateCertificateRequest(name, namespace string) *certmanagerv1.CertificateRequest {
	return kubernetes.Create[certmanagerv1.CertificateRequest](name, namespace)
}

// CreateChallenge returns a acme.cert-manager.io/v1 Challenge carrying TypeMeta and identity only.
func CreateChallenge(name, namespace string) *acmev1.Challenge {
	return kubernetes.Create[acmev1.Challenge](name, namespace)
}

// CreateClusterIssuer returns a cluster-scoped cert-manager.io/v1 ClusterIssuer carrying TypeMeta and identity only.
func CreateClusterIssuer(name string) *certmanagerv1.ClusterIssuer {
	return kubernetes.Create[certmanagerv1.ClusterIssuer](name, "")
}

// CreateIssuer returns a cert-manager.io/v1 Issuer carrying TypeMeta and identity only.
func CreateIssuer(name, namespace string) *certmanagerv1.Issuer {
	return kubernetes.Create[certmanagerv1.Issuer](name, namespace)
}

// CreateOrder returns a acme.cert-manager.io/v1 Order carrying TypeMeta and identity only.
func CreateOrder(name, namespace string) *acmev1.Order {
	return kubernetes.Create[acmev1.Order](name, namespace)
}
