// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package metallb

import (
	"testing"

	"sigs.k8s.io/controller-runtime/pkg/client"
)

func TestGeneratedConstructors(t *testing.T) {
	cases := []struct {
		kind       string
		namespaced bool
		obj        client.Object
	}{
		{"BFDProfile", true, CreateBFDProfile("name", "ns")},
		{"BGPAdvertisement", true, CreateBGPAdvertisement("name", "ns")},
		{"BGPPeer", true, CreateBGPPeer("name", "ns")},
		{"Community", true, CreateCommunity("name", "ns")},
		{"ConfigurationState", true, CreateConfigurationState("name", "ns")},
		{"IPAddressPool", true, CreateIPAddressPool("name", "ns")},
		{"L2Advertisement", true, CreateL2Advertisement("name", "ns")},
		{"ServiceBGPStatus", true, CreateServiceBGPStatus("name", "ns")},
		{"ServiceL2Status", true, CreateServiceL2Status("name", "ns")},
	}
	for _, c := range cases {
		t.Run(c.kind, func(t *testing.T) {
			if got := c.obj.GetObjectKind().GroupVersionKind().Kind; got != c.kind {
				t.Errorf("kind = %q, want %q", got, c.kind)
			}
			wantNS := ""
			if c.namespaced {
				wantNS = "ns"
			}
			if c.obj.GetName() != "name" || c.obj.GetNamespace() != wantNS {
				t.Errorf("identity = %s/%s, want %s/name", c.obj.GetNamespace(), c.obj.GetName(), wantNS)
			}
		})
	}
}
