// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package metallb

import (
	metallbv1beta1 "go.universe.tf/metallb/api/v1beta1"

	"github.com/go-kure/kure/pkg/kubernetes"
)

// CreateBFDProfile returns a metallb.io/v1beta1 BFDProfile carrying TypeMeta and identity only.
func CreateBFDProfile(name, namespace string) *metallbv1beta1.BFDProfile {
	return kubernetes.Create[metallbv1beta1.BFDProfile](name, namespace)
}

// CreateBGPAdvertisement returns a metallb.io/v1beta1 BGPAdvertisement carrying TypeMeta and identity only.
func CreateBGPAdvertisement(name, namespace string) *metallbv1beta1.BGPAdvertisement {
	return kubernetes.Create[metallbv1beta1.BGPAdvertisement](name, namespace)
}

// CreateBGPPeer returns a metallb.io/v1beta1 BGPPeer carrying TypeMeta and identity only.
func CreateBGPPeer(name, namespace string) *metallbv1beta1.BGPPeer {
	return kubernetes.Create[metallbv1beta1.BGPPeer](name, namespace)
}

// CreateCommunity returns a metallb.io/v1beta1 Community carrying TypeMeta and identity only.
func CreateCommunity(name, namespace string) *metallbv1beta1.Community {
	return kubernetes.Create[metallbv1beta1.Community](name, namespace)
}

// CreateConfigurationState returns a metallb.io/v1beta1 ConfigurationState carrying TypeMeta and identity only.
func CreateConfigurationState(name, namespace string) *metallbv1beta1.ConfigurationState {
	return kubernetes.Create[metallbv1beta1.ConfigurationState](name, namespace)
}

// CreateIPAddressPool returns a metallb.io/v1beta1 IPAddressPool carrying TypeMeta and identity only.
func CreateIPAddressPool(name, namespace string) *metallbv1beta1.IPAddressPool {
	return kubernetes.Create[metallbv1beta1.IPAddressPool](name, namespace)
}

// CreateL2Advertisement returns a metallb.io/v1beta1 L2Advertisement carrying TypeMeta and identity only.
func CreateL2Advertisement(name, namespace string) *metallbv1beta1.L2Advertisement {
	return kubernetes.Create[metallbv1beta1.L2Advertisement](name, namespace)
}

// CreateServiceBGPStatus returns a metallb.io/v1beta1 ServiceBGPStatus carrying TypeMeta and identity only.
func CreateServiceBGPStatus(name, namespace string) *metallbv1beta1.ServiceBGPStatus {
	return kubernetes.Create[metallbv1beta1.ServiceBGPStatus](name, namespace)
}

// CreateServiceL2Status returns a metallb.io/v1beta1 ServiceL2Status carrying TypeMeta and identity only.
func CreateServiceL2Status(name, namespace string) *metallbv1beta1.ServiceL2Status {
	return kubernetes.Create[metallbv1beta1.ServiceL2Status](name, namespace)
}
