// Code generated by pkg/kubernetes/internal/gen; DO NOT EDIT.
// Source: the registered scheme (RegisterSchemes) and the scope table in internal/kinds.

package volsync

import (
	volsyncv1alpha1 "github.com/backube/volsync/api/v1alpha1"

	"github.com/go-kure/kure/pkg/kubernetes"
)

// CreateReplicationDestination returns a volsync.backube/v1alpha1 ReplicationDestination carrying TypeMeta and identity only.
func CreateReplicationDestination(name, namespace string) *volsyncv1alpha1.ReplicationDestination {
	return kubernetes.Create[volsyncv1alpha1.ReplicationDestination](name, namespace)
}

// CreateReplicationSource returns a volsync.backube/v1alpha1 ReplicationSource carrying TypeMeta and identity only.
func CreateReplicationSource(name, namespace string) *volsyncv1alpha1.ReplicationSource {
	return kubernetes.Create[volsyncv1alpha1.ReplicationSource](name, namespace)
}
